apiVersion: jenkins.io/v1
kind: Environment
metadata:
  creationTimestamp: null
  name: production
spec:
  kind: Permanent
  label: Production
  namespace: aks-test-production
  order: 200
  previewGitInfo:
    user: {}
  promotionStrategy: Manual
  source:
    ref: master
    url: https://github.com/BoC-Build-Bot/environment-bowcandy-production.git
  teamSettings:
    defaultScheduler:
      kind: ""
      name: ""
status: {}
