# Override configuration from https://github.com/jenkins-x/jenkins-x-platform/blob/master/jenkins-x-platform/values.yaml

PipelineSecrets:

  # lets enable ACR docker builds
  DockerConfig: |-
    {
      "credsStore": "acr-linux"
    }
    
docker-registry:
  enabled: false    
auth:
  git:
    username: boc-build-bot
build:
  enabled: false
buildnum:
  enabled: false
pipelinerunner:
  enabled: "true"
tillerNamespace: ""
